jobs:
- name: daily
  schedule: 0 12 * * * # This example will run every day at 12:00pm
  steps:
     - name: version
       command: dbt --version
- name: daily_metrics
  schedule: 0 12 * * * # This example will run every day at 12:00pm
  steps:
     - name: daily_metrics
       command: dbt run --models models\github__daily_metrics.sql